name: news
description: A new Flutter application to learn http requests and sqlite.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  sqflite: ^1.1.0
  path_provider: ^0.4.1
  http: ^0.12.0+4
  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
